version: '3'

services:
    app:
        build: .
        container_name: app
        volumes:
            - .:/var/www
        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 20s ./.docker/entrypoint.sh
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        networks:
            - app-network
        depends_on:
            - db
            - redis
    nginx: 
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes: 
            - .:/var/www
        entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf ./.docker/nginx/entrypoint.sh
        environment: 
            - APP_PORT=9000
            - APP_HOST=app
        networks:
            - app-network
        depends_on:
            - app
            
    db:
        build: .docker/mysql
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network
        # Somente versão 2.3 <
        #healthcheck:
        #    test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT COUNT(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
        #    interval: 10s
        #    timeout: 10s
        #    retries: 4

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network
networks:
    app-network:
        driver: bridge